spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/spring_study?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1111

  jpa:
#    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        format_sql: true #To beautify or pretty print the SQL
#        show_sql: true #show sql
        default_batch_fetch_size: 100

logging:
    level:
      org.hibernate.SQL: debug  #하이버네이트가 생성하는 SQL 콘솔로깅
      org.hibernate.type: trace #쿼리 파라미터 로그 남기기

